### ISSUE TITLE
你好，加压密码是不公开还是理解问题？

### ISSUE THREAD

**Issue by lpcdma** [SCUBSRGroup/OLLVM_Deobfuscation#6]
APlus123
我的名字
SCUBSRGroup
OLLVM_Deobfuscation
都测试了不能解压

**Comment by APlus123** [comment]
你好，由于某些其他原因，将在11月份解除密码限制，带来的不便还请谅解

**Comment by liumengdeqq** [comment]
貌似还是没有解除限制啊

**Comment by APlus123** [comment]
@liumengdeqq  @lpcdma 实在抱歉，可能要推迟到1月下旬公开了

**Comment by liumengdeqq** [comment]
我看了x86是有CMOV 识别的 arm的控制流平坦化 你们怎么识别呢

**Comment by APlus123** [comment]
@liumengdeqq  arm的指令规则不像x86那么明显，需要重新分析规则，难点还是在指令的识别上，目前我也还在研究中

**Comment by liumengdeqq** [comment]
angr不是能识别arm的指令么

**Comment by APlus123** [comment]
angr的确能识别arm的指令，但angr获得的CFG和IDA有差异，所以在OLLVM反混淆中主要是使用BARF框架进行指令反汇编以及basicblock分析，以保证程序CFG和IDA的一致性，并使用angr进行符号执行，得到真实基本块间的拓扑关系，难点就是在真实基本块的识别上（BARF也支持ARM指令的分析），你也可以尝试下只用angr完成反混淆（只用angr也是能完成反混淆的）。

**Comment by liumengdeqq** [comment]
我发现angr对arm的支持有bug

**Comment by Hilo1989** [comment]
18年1月末了，请问现在解除密码限制了么？down下来后还是解不出来，如果不能公开的话放在这里是不是有点...

**Comment by lpcdma** [comment]
https://github.com/liumengdeqq/deflat
@Hilo1989

**Comment by usualwyy** [comment]
你在项目中引入了miasm框架，miasm是GPL v2协议，你用了人家的框架，不仅不开源，还加上密码放到github这个开源社区里，不知道阁下有没有一点最基本的职业道德观念。

**Comment by APlus123** [comment]
@usualwyy 阁下实在抱歉，最近太忙，忘了维护了，本周内会上传最新的改善版本，并完全开源，另外：本反混淆框架中并没有使用Miasm框架  只是将其作为反混淆结果对照

**Comment by awskkzl** [comment]
您论文中的工作似乎也是之前腾讯安全实验室别人完成的deflat部分吧。。。miasm这部分也是2014年的工作吧。。。

**Comment by APlus123** [comment]
@awskkzl 你好，这个项目借鉴了其思想，并做了进一步改良，同样采用angr作为符号执行框架 （优化并去除了其他无用的基本块，使其和原未混淆程序CFG更为接近，在基本块识别和指令修复上有所改进）
Miasm那个代码只是2014年的单个基本块的符号执行样例，只是简单作为对比 并没有列出完整的反混淆代码  后面会给出最新优化后的详细代码
